### ISSUE TITLE
Release a non snapshot version

### ISSUE THREAD

**Issue by mynomoto** [honzabrecka/karma-reporter#1]
Hi,

First, thank you for this project. I like it so much that I would like to ask for the release of `0.1.0` so I could use it without having to worry about changes on the snapshot if it's not too much trouble for you.

Thanks again!

**Comment by honzabrecka** [comment]
Yes, I'll do it tomorrow!

**Comment by honzabrecka** [comment]
Done.

**Comment by mynomoto** [comment]
Thanks!
