### ISSUE TITLE
Possibly make karma reporter derive from default reporter

### ISSUE THREAD

**Issue by bhb** [honzabrecka/karma-reporter#11]
Currently, if another project uses a custom report type, by default it will not be printed when using karma. This caused me confusion when using `test.chuck` - see https://github.com/gfredericks/test.chuck/issues/52.

I understand that for karma, we don't want to print some report types, namely the `:cljs.test/summary` type that is (presumably intentionally) not implemented in `karma-reporter`. However, what do you think about making a blank implementation for that report type e.g.

```clojure
(defmethod cljs.test/report [::karma :summary] [_]
  ;; do nothing 
)
```

and then have the karma reporter derive from the default:

```clojure
(derive :jx.reporter.karma/karma :cljs.test/default)
```

I believe that would:

* keep the existing behavior of not printing the summary
* by default, print any new report types that are defined for the default reporter. Clients could then implement those multimethods if they did not want to see them, but they would not be missing by default.

What do you think?

**Comment by honzabrecka** [comment]
I understand your issue and agree that it's something we should support. Would you mind open PR?
