### ISSUE TITLE
Handle post condition failures

### ISSUE THREAD

**Issue by danielcompton** [honzabrecka/karma-reporter#14]
This function will break the Karma output reporter:

```clj
(defn simple-fn [x]
  {:post [(= x 1)]}
  x)

(deftest simple-test
  (is (simple-fn 2)))
```

```
Chrome 56.0.2924 (Mac OS X 10.12.3) ERROR
  Uncaught Error: Error: Assert failed: (= x 1) is not ISeqable
  at run/resources/public/compiled_karma/cljs/core.js:4179
```

It looks like the error is being thrown here: https://github.com/honzabrecka/karma-reporter/blob/2.1.0/src/jx/reporter/karma.cljs#L72. `actual` is the error that was thrown in the postcondition, `second` is being called on the error, which is throwing the ISeqable error.

**Comment by danielcompton** [comment]
I'm not actually sure post conditions are the problem, this test will also break the reporter:

```
(deftest simple-test
  (is false))
```

Version 1.0.1 works correctly.

**Comment by honzabrecka** [comment]
Thanks for the report. Fixed.

**Comment by danielcompton** [comment]
Awesome, thanks! Are you able to make a new release?

**Comment by honzabrecka** [comment]
Just pushed 2.1.2 release.

**Comment by danielcompton** [comment]
Thanks!
