### ISSUE TITLE
testing context not displayed in test output

### ISSUE THREAD

**Issue by Dexterminator** [honzabrecka/karma-reporter#15]
It seems like only the cljs.test/testing-vars-str is used in:
https://github.com/honzabrecka/karma-reporter/blob/2c268b4b72a2b2aee693949d3f55cbaea515c118/src/jx/reporter/karma.cljs#L58-L72

The cljs.test/testing-contexts-str should be displayed as well in order to get any value from using the (testing) macro.

**Comment by honzabrecka** [comment]
Would you mind to send PR?

**Comment by Dexterminator** [comment]
Will do when I find the time!
