### ISSUE TITLE
Fix invalid aget use

### ISSUE THREAD

**Issue by Deraen** [honzabrecka/karma-reporter#17]
Looks like there is at least single place where Karma-reporter is using `aget` to access a object.

To test use `:checked-arrays :warn`.

https://github.com/honzabrecka/karma-reporter/blob/master/src/jx/reporter/karma.cljs#L21

```
WARNING: cljs.core/aget, arguments must be an array followed by numeric indices, got [js string] instead (consider goog.object/get for object access) at line 20 /home/juho/.cljs/.aot_cache/1.10.238/B8770A6/jx/reporter/karma.cljs
```

Fix would be to use `goog.object/get` instead.

**Comment by honzabrecka** [comment]
Thanks! Fixed.
